export const DEFAULT_SETTINGS = {
  CLAUDE_MEM_MODEL: 'claude-sonnet-5',
  CLAUDE_MEM_CONTEXT_OBSERVATIONS: '50',
  CLAUDE_MEM_SESSION_START_INCLUDE_ALL_SOURCES: 'false',
  CLAUDE_MEM_WORKER_PORT: '37700',
  CLAUDE_MEM_WORKER_HOST: '127.0.0.1',

  CLAUDE_MEM_PROVIDER: 'claude',
  CLAUDE_MEM_CODEX_MODEL: '',
  CLAUDE_MEM_GEMINI_API_KEY: '',
  CLAUDE_MEM_GEMINI_API_KEYS: '',
  CLAUDE_MEM_GEMINI_MODEL: 'gemini-flash-latest',
  CLAUDE_MEM_OPENROUTER_API_KEY: '',
  CLAUDE_MEM_OPENROUTER_API_KEYS: '',
  CLAUDE_MEM_OPENROUTER_MODEL: 'cohere/north-mini-code:free',
  CLAUDE_MEM_OPENROUTER_BASE_URL: '',
  CLAUDE_MEM_OPENROUTER_SITE_URL: '',
  CLAUDE_MEM_OPENROUTER_APP_NAME: 'claude-mem',
  CLAUDE_MEM_OPENROUTER_REASONING_EFFORT: '',
  CLAUDE_MEM_GEMINI_RATE_LIMITING_ENABLED: 'true',
  CLAUDE_MEM_QUOTA_FALLBACK_PROVIDER: '',
  CLAUDE_MEM_QUOTA_FALLBACK_MODEL: '',

  // The generic OpenAI-compatible provider (NVIDIA NIM and friends).
  CLAUDE_MEM_OPENAI_COMPAT_PRESET: '',
  CLAUDE_MEM_OPENAI_COMPAT_API_KEY: '',
  CLAUDE_MEM_OPENAI_COMPAT_API_KEYS: '',
  CLAUDE_MEM_OPENAI_COMPAT_BASE_URL: '',
  CLAUDE_MEM_OPENAI_COMPAT_MODEL: '',

  CLAUDE_MEM_CONTEXT_SHOW_READ_TOKENS: 'false',
  CLAUDE_MEM_CONTEXT_SHOW_WORK_TOKENS: 'false',
  CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_AMOUNT: 'false',
  CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_PERCENT: 'true',

  CLAUDE_MEM_CONTEXT_FULL_COUNT: '0',
  CLAUDE_MEM_CONTEXT_FULL_FIELD: 'narrative',
  CLAUDE_MEM_CONTEXT_SESSION_COUNT: '10',

  CLAUDE_MEM_CONTEXT_SHOW_LAST_SUMMARY: 'true',
  CLAUDE_MEM_CONTEXT_SHOW_LAST_MESSAGE: 'false',
  CLAUDE_MEM_FILE_READ_GATE_ENABLED: 'true',
  CLAUDE_MEM_CONTEXT_MAIN_AGENT_ONLY: 'true',

  CLAUDE_MEM_SKIP_SUBAGENT_OBSERVATIONS: 'false',
  CLAUDE_MEM_SKIP_AGENT_TYPES: '',
} as const;
